services:
  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Main
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - bankservices_dbnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - bankservices_dbnet

  bankservices:
    image: bankservices
    build:
      context: src
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgresdb;Port=5432;Database=Main;Username=postgres;Password=postgres;"
    depends_on:
      - postgresdb
    networks:
      - bankservices_dbnet
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  bankservices_dbnet:
    driver: bridge
